config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :users  
  resources :books
  
  post 'books/search' => 'books#search', as: 'search'

  root to: "books#top"
  get 'home/about' => 'homes#about', as:"about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_one_attached :profile_image
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  acts_as_taggable_on :tags
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :name, presence: true, length: { in: 2..20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
     user_path(resource)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end
  
  protected

  # emailをkeyとしてログインを行う
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  # def new
  #   @book_new = Book.new
  # end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book.id)
    else
    @user = current_user
    @books = Book.all
    # @book = Book.new
    render :index
    end
  end
  
  def top
    
  end

  def show
    # @user = current_user
    # @book_new = Book.new
    @book = Book.find(params[:id])  
    @user = @book.user
    @books =Book.all
  end

  def index
    @book = Book.new
    @user = current_user
    @books = Book.all
  end

  def edit
    # @book_new = Book.new
    @user = current_user
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book)
    else
      render :edit
    end
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to '/books'
  end

  def search
    @keyword = params[:keyword]
    @books = Book.where('title LIKE ? OR body LIKE ?', "%#{@keyword}%", "%#{@keyword}%")

    @book = Book.new
    @user = current_user
    render :index
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body, :tag_list)
  end


  def is_matching_login_user
    book = Book.find(params[:id])
    user = book.user
    unless user.id == current_user.id
      redirect_to books_path
    end
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  
  
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def show
    @user = User.find_by(id: params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user)
    else
      @users = User.all
      render :edit
    end
    # if @user.update(user_params) # ユーザーの属性を更新
    # redirect_to user_path(@user) # ユーザーの詳細ページへのリダイレクト
    # else
    # render :edit # 更新に失敗した場合は編集ページを再表示
    # end
  end
  
   private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def is_matching_login_user
    user = User.find(params[:id])
    unless user == current_user
      redirect_to user_path(current_user.id)
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookers_helper.rb
module BookersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_template.html.erb
<h1>User info</h1>
<table class="table">
  <tr>
    <%= image_tag user.get_profile_image(100, 100) %>
  </tr>
  <tr>
    <th>name</th>
    <th><%= user.name %></th>
  </tr>
  <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
  </tr>
</table>

<div class="row">
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>  
  ユーザー編集
  <% end %>
</div>

<% if book.errors.any? %>
  <div>
    <%= book.errors.count %> error prohibited this obj from being saved:
    <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h1>New book</h1>
<%= form_with model: book do |f| %>
  <div>
    <h4>Title</h4>
    <%= f.text_field :title %>
  </div>
  
  <div>
    <h4>Opinion</h4>
    <%= f.text_area :body %>
  </div>

  <div class="form-group form-group_tags">
    <%= f.label :tag_list, "Tag", class: "form-label" %>
    <%= f.text_field :tag_list, id: "tag_input", class: "form-control", data: { role: "tagsinput" } %>
    <%= f.hidden_field :tag_list, id: "tag_list_hidden" %>
  </div>

  <%= f.submit 'Create Book', class: "btn btn-success" %>
<% end %>

<style>
#tag_input {
  min-width: 100px;
}

.tag.label.label-info {
  margin-right: 5px;
  padding: 5px;
  background-color: #f0f0f0;
  border-radius: 5px;
}
</style>

app/views/books/edit.html.erb
<%#= form_with model: @book, url: update_list_path(@book.id), method: :patch do |f| %>
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>



<%= form_with model: @book do |f| %>
<h1>Editing Book</h1>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>opinion</h4>
  <%= f.text_area :body %>
  
<%= f.submit 'Update Book' %>
 <% if @book.user == current_user %>
   <td><%= link_to "Show", book_path(@book.id) %></td>
   <td><%= link_to "Back", books_path %></td>  
<% end %>
<% end %>

app/views/books/index.html.erb
<div>
  <%= flash[:notice] %>
</div>

<% if @books.any? %>
  <% @books.each do |book| %>
    <% if book.errors.any? %>
      <%= book.errors.count %> error prohibited this obj from being saved:
      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  <% end %>
<% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'template', user: @user, book: @book %>
    </div>
  <div class="col-md-8 offset-md-1">
    <%= form_with url: search_path, local: true do |f| %>
      <div class="form-group">
        <%= f.label :keyword %>
        <%= f.text_field :keyword, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.submit 'search', class: 'btn btn-primary' %>
      </div>
    <% end %>
    <h1>Books</h1>
    <table class='table table-hover table-inverse'>
      <thead>
        <tr>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
                <%= image_tag book.user.get_profile_image(100, 100) %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/books/show.html.erb
<div>
  <%= flash[:notice] %>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-3">    
      <%= render 'template', user: @user, book: Book.new %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h1>Book detail</h1>
      <table class="table">
        <tr>
          <td>
            <%= image_tag @user.get_profile_image(100, 100) %>
            <h4><%= link_to @user.name, user_path(@user.id) %></h4>
          </td>
          <td><%= link_to @book.title, book_path(@book.id) %></td>
          <td><%= @book.body %></td>
          <td>
            <% @book.tag_list.each do |tag| %>
              <span><%= tag %></span>
            <% end %>
          </td>
          <% if @book.user == current_user %>
            <td><%= link_to "Edit", edit_book_path(@book.id) %></td>
            <td><%= link_to "Destroy", book_path(@book.id), method: :delete, data: { confirm: "本当に削除しますか？" } %></td>  
          <% end %>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/books/top.html.erb
<div>
  <%= flash[:notice] %>
</div>


<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>

<h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong>  !!</h1>
<p>In <i class="fa-solid fa-book"></i><strong>Bookers</strong>, </p>
<p>you can share and exchange your opinions , inpressions , and emotions</p>
<p>about various books!</p>

 <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3" %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block" %>
        </div>
      </div>
    </div>
  </div>  
</div>

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">
      Welcome to<i class="fas fa-book"></i>
      <strong>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<h1>homes top</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
<script src="https://kit.fontawesome.com/041e521652.js" crossorigin="anonymous"></script>


    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      
      <nav class="navbar navbar-expand-lg navbar-light navbar-dark bg-dark">
    <div class="container">
      <%= link_to "Bookers", root_path,class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          
     <% if user_signed_in? %>
      <li>
      <%= link_to user_path(current_user.id), class: "nav-link text-light" do%>
         <i class="fas fa-home"></i> Home
        <% end %>
      </li>
      
      <li>
         <%= link_to users_path, class: "nav-link text-light" do%>
         <i class="fa-solid fa-users"></i> Users
        <% end %>
      </li>
      
      <li><%= link_to books_path, class: "nav-link text-light" do%>
      <i class="fa-solid fa-book-open"></i> Books
      <% end %>
      </li>
      
      <li><%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
      <i class="fa-solid fa-right-from-bracket"></i> Log out
      <% end %>
      </li>
      
      
    <% else %>
      <li><%= link_to root_path, class: "nav-link text-light" do %>
      <i class="fa-solid fa-house"></i> Home
      <% end %>
      </li>
      
      <li><%= link_to about_path, class: "nav-link text-light" do %>
      <i class="fa-solid fa-link"></i> About
      <% end %>
      </li>
      
      <li><%= link_to new_user_registration_path, class: "nav-link text-light" do %>
      <i class="fa-solid fa-user-plus"></i> Sign up
      <% end %>
      </li>
      
      <li><%= link_to new_user_session_path, class: "nav-link text-light" do %>
      <i class="fa-solid fa-right-to-bracket"></i> Log in
      <% end %>
      </li>
      
    <% end %>
    </ul>
    </div>
    </div>
    </nav>
  </header>


    <%= yield %>
    
    <footer>
      <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
      <p>CopyRight Infratop.inc</p>
       </div>
      </div>
    </div>
    </footer>
    
  </body>
</html>

app/views/users/edit.html.erb
<div>
  <%= flash[:notice] %>
</div>

<h2>User info</h2>

<% if @user.errors.any? %>
  <div>
    <%= @user.errors.count %> errors prohibited this object from being saved:
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @user do |f| %>
  <div class="form-group">
    <label for="inputName">Name</label>
    <div><%= f.text_field :name, autofocus: true, id: "inputName", placeholder: "名前" %></div>
  </div>
  
  <div class="form-group">
    <label for="inputImage">Image</label>
    <div><%= f.file_field :profile_image, id: "inputImage", placeholder: "プロフィール画像", accept: "image/*" %></div>
  </div>
  
  <div class="form-group">
    <label for="inputIntroduction">Introduction</label>
    <div><%= f.text_area :introduction, id: "inputIntroduction" %></div>
  </div>
  
  <div class="actions">
    <%= f.submit "Update User", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/index.html.erb
<div>
  <%= flash[:notice] %>
</div>

<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <%= render 'books/template', user: @user, book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h1>Users</h1>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= link_to users_path do %>
                  <%= image_tag user.get_profile_image(100, 100) %>
                <% end %>
              </td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div>
  <%= flash[:notice] %>
</div>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/template',user: @user, book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= image_tag book.user.get_profile_image(100, 100) %>
                  <%= link_to "プロフィール編集", users_path(:id) %>
                <% end %>
              </td>
              <td><%= link_to book.title ,book_path(book.id)%></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>